### ISSUE TITLE
Frontend: Search field does not show locally

### ISSUE THREAD

**Issue by petterwildhagen** [equinor/dcd#180]

**Comment by valentin-krasontovitsch** [comment]
having same issue. seems like the environment variable `REACT_APP_API_BASE_URL` needs to be set or get a default value.

starting the frontend with `env REACT_APP_API_BASE_URL='http://localhost:5000' npm run start` brought up the frontend, which showed the search bar (assuming of course that the backend is running at `localhost:5000`)

**Comment by valentin-krasontovitsch** [comment]
ping @aronhoyer in case you were working on this / looking at this
