### ISSUE TITLE
DCD backend: create swagger.json api docs

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [equinor/dcd#183]
for creating a client based on the api docs (cf. #68) we need to have the docs available as a file, e.g. `swagger.json` - we should find a convenient way of generating this file, and perhaps add it to our version control, where convenient means automated and reproducible.

**Comment by valentin-krasontovitsch** [comment]
at the moment it can be downloaded / looked at from the swagger web ui at the top of the page
![swagger json](https://user-images.githubusercontent.com/15932677/151951261-655b2498-cea6-4f46-a31e-0e066f0fdd77.png)

**Comment by valentin-krasontovitsch** [comment]
regarding automatic generation - [apparently it's difficult with swashbuckle](https://github.com/domaindrivendev/Swashbuckle.WebApi/issues/559)

**Comment by daskabe** [comment]
Hi, I'm currently working on deploying a .net core api project to azure.  

Azure app services needs the openAPI specification to populate the api definitions. 
In process of deploying through github actions CI/CD pipeline; I found that the VisualStudio generated pipeline yml includes this step.

```
 - name: Generate Open API Specification Document
      run: swagger tofile --output "${{ env.API_IMPORT_SPECIFICATION_PATH }}" "${{ env.API_IMPORT_DLL }}" "${{ env.API_IMPORT_VERSION }}"
```

This blog post has details on how to generate swagger.json as build output.
https://medium.com/@woeterman_94/how-to-generate-a-swagger-json-file-on-build-in-net-core-fa74eec3df1

I hope it helps.
