### ISSUE TITLE
DCD Frontend: Create Transport asset with time series for cost profile using relative years

### ISSUE THREAD

**Issue by petterwildhagen** [equinor/dcd#325]

**Comment by InGit5** [comment]
**Akseptansekriterier:**
Gitt at jeg er innlogget som Concept Architect skal jeg kunne opprette en Transport Asset på en Case.
Gitt at jeg er innlogget som Concept Architect og legger til en Transport Asset skal jeg kunne gi den et navn og en beskrivelse og sette en DG4-dato.
Gitt at jeg er innlogget som Concept Architect skal jeg enkelt kunne få oversikt over hvilke Assets som er knyttet til en Case.
Gitt at jeg er innlogget som en Concept Architect skal jeg få oversikt over kostprofilen/detaljene til en Asset og det totale kostnadsbildet til en Case.

Gitt at jeg er innlogget som en Engineer som skal utføre beregninger skal jeg enkelt kunne få oversikt over hvilke forutsetninger jeg skal legge til grunn for mine beregninger for min Asset på det spesifikke Caset.
Gitt at jeg er innlogget som en Engineer og skal legge inn kostprofil for min Asset skal jeg enkelt finne ut hvilken Asset jeg skal oppdatere og kunne legge inn start-dato for min kostnadsprofil og deretter kunne lime inn og lagre data fra min excel-fil (eventuelt også andre systemer enn excel).

Gitt at det har blitt lagt til en kostprofil på et Transport Asset skal kostprofilen bli lagt til den totale kostprofilen for Caset.
