### ISSUE TITLE
Cannot create case (401)

### ISSUE THREAD

**Issue by petterwildhagen** [equinor/dcd#375]

**Comment by petterwildhagen** [comment]
When creating case a 401 (unauthorized appears in the console)

**Comment by DanielBohme** [comment]
Need to check further, but currently Ctrl + F5 fixes the issue temporarily

**Comment by fredrikleknes** [comment]
@DanielBohme check if #393 fixed the issue

**Comment by petterwildhagen** [comment]
> @DanielBohme check if #393 fixed the issue

Problem still exists. It seems there is a 401 on trying to access the /cases api (to create the case).
