### ISSUE TITLE
Capex per case not shown in project view

### ISSUE THREAD

**Issue by petterwildhagen** [equinor/dcd#376]

**Comment by petterwildhagen** [comment]
![image](https://user-images.githubusercontent.com/16671886/157414235-53f2cc8f-8b6f-44bf-b362-66ba5c879dd9.png)

Table should show capex per case - Capex is an attribute on the case object.

**Comment by ManveerPandher** [comment]
When going into the commit after the one above
![image](https://user-images.githubusercontent.com/100352897/157683542-b042c6af-51ec-49a3-8271-5ec4c19b8f28.png)

I do no longer get the bars. 
![image](https://user-images.githubusercontent.com/100352897/157683587-75e05be4-5bca-4e32-a177-a49c68c80381.png)

**Comment by ManveerPandher** [comment]
Approved and merged in Main.
Source branch deleted
Moved to "Done"
