### ISSUE TITLE
DCD: Find project dialog does not show when application is first opened

### ISSUE THREAD

**Issue by petterwildhagen** [equinor/dcd#407]
When starting up the concept application the 'Find a project' selector is not displayed (user needs to refresh)

**Comment by petterwildhagen** [comment]
![image](https://user-images.githubusercontent.com/16671886/158555142-6429da2f-c105-44e2-8199-9d534a958a24.png)

**Comment by ManveerPandher** [comment]
After a conversation with @petterwildhagen, we decided to not investigate further on this non-reproducable bug.
<img width="767" alt="image" src="https://user-images.githubusercontent.com/100352897/158963206-c42c4825-fb6a-47d8-bdf8-475c64a923c0.png">

**Comment by petterwildhagen** [comment]
Occurs when I check out https://github.com/equinor/dcd/pull/423
