### ISSUE TITLE
DCD Frontend: Miscellaneous visual improvements

### ISSUE THREAD

**Issue by ManveerPandher** [equinor/dcd#424]

**Comment by InGit5** [comment]
Se over og forbedre GUI for case med flere tidsserieinput, eks: 
![image](https://user-images.githubusercontent.com/98051475/161713950-6974c321-1de3-4146-bee8-f2cd187d3bae.png)

**Comment by InGit5** [comment]
Create Case -> Drainage strategy - Drainage strategy does not display asset category name as page header.
Create Case -> Case name box is small - long names does not show. 
SURF is written with capital letters in Case view, small letters in Asset
