### ISSUE TITLE
DCD: Possible to create multiple projects from same commonlib project

### ISSUE THREAD

**Issue by fredrikleknes** [equinor/dcd#439]

**Comment by InGit5** [comment]
Akseptansekriterier: 
- Gitt at jeg som Konseptarkitekt skal opprette et nytt prosjekt i DCD skal jeg kunne finne prosjektet i CommonLib.
- Gitt at jeg som Konseptarkitekt skal opprette et nytt prosjekt i DCD skal det ikke være mulig å opprette et prosjekt fra CommonLib hvis det allerede er opprettet et prosjekt i DCD. 
- Gitt at jeg som Konseptarkitekt forsøker å opprette et nytt prosjekt hvis CommonLib-prosjektet allerede ligger i DCD skal jeg få en feilmelding.
