### ISSUE TITLE
DCD: Add Cessation cost to offshore Facilities 

### ISSUE THREAD

**Issue by petterwildhagen** [equinor/dcd#494]

**Comment by ManveerPandher** [comment]
For Assets:
* Surf
* Topside
* Substructure
* Transport

There should be possible to add another Cost Profile (Cessation).

This affects Backend, frontend and Excel.

Model update command needs also to be ran sometime.

**Comment by ManveerPandher** [comment]
![image](https://user-images.githubusercontent.com/100352897/161965981-9a94610d-a6a7-4faf-9f82-7b97a794ce4f.png)

**Comment by ManveerPandher** [comment]
npm run autogenerate-models

**Comment by InGit5** [comment]
Acceptance criteria:
Given that there is a project and a case with asset surf/topside/substructure/transport, when the engineer have calculated cessation costs for an asset then it should be possible to add the cost profiles to the individual assets.
Given that cessation costs have been added to an asset, when the concept architect want to compare business cases then the cessation cost should be included in the CAPEX/Cost for that case.
Given that cessation costs have been added to an asset, when the concept architect want to export data to STEA the cessation cost profile should be included in the export.
...

**Comment by petterwildhagen** [comment]
![image](https://user-images.githubusercontent.com/16671886/162392581-ae3d13a2-2ce5-41f1-b48d-d5c24c6a3f78.png)
