### ISSUE TITLE
DCD: Add ArtificialLift to Case model

### ISSUE THREAD

**Issue by ahmedoabdi** [equinor/dcd#546]
Add the metadata Artifical lift to Case model

**Comment by fredrikleknes** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/22823836/164472494-5281cd61-aebf-43d8-b9d8-3e97b9050ff2.png)

**Comment by fredrikleknes** [comment]
Picture above describes how Artificial Lift should be implemented on case level. A dropdown should be visible and options are:
- GasLift
- NoArtificialLift
- ElectricalSubmergedPumps
- SubseaBoosterPumps

This is all confirmed by Atle
