### ISSUE TITLE
DCD Frontend: Add remaining metadata to surf

### ISSUE THREAD

**Issue by fredrikleknes** [equinor/dcd#572]

**Comment by InGit5** [comment]
Test: Validated that metadata in line with the data model are displayed and editable in the asset view:

Cost profile - OK
Maturity [enum] - OK
Length of production lines[measurement] - OK
Length of umbilical system [measurement] - OK
Production flowline [enum] - _missing_
Riser count [int] - OK, inherited from Case
Template count [int] - OK, inherited from Case
Artificial lift [enum] - OK, inherited from Case
Cessation cost [cost profile] - OK
