### ISSUE TITLE
DCD Frontend: Add remaining metadata to transport

### ISSUE THREAD

**Issue by DanielBohme** [equinor/dcd#584]

**Comment by InGit5** [comment]
Test: validated that the metadata fields are shown and editable and can be saved. Changes are shown on other asset if linked.
- [ x] Cost profile
- [ x] Length of gas export pipeline [measurement]
- [ x] Length of oil export pipeline [measurement]
- [ x] Maturity [enum]
- [ x] Cessation cost [cost profile]
