### ISSUE TITLE
DCD Frontend: Fix labels on metadata

### ISSUE THREAD

**Issue by DanielBohme** [equinor/dcd#606]
Fixed labels for Dryweight to specified per asset using it (example Topside dry weight). Also fixed casing on labels as there was different casing all around the place.

**Comment by InGit5** [comment]
Substructure and Topside have dry weight named as "Topside dry weight" and "Substructure dry weith" in the excel table. At the moment this is implemented as only "Dry weight" on both assets in Front End – should use the full name Front End as well.
